pipeline {
    agent any

    parameters {
        string(name: 'PERSON2', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        string(name: 'PERSON212e12e1', defaultValue: 'Mr Jenkins2', description: 'Who should I say hello to?2')
    }
    stages {
        stage('Checkout') { 
            steps {
                git credentialsId: "${github_creds}" , url: "${github_repo}" 
            }
        }
    }
  }
