pipeline {
    agent any
    
    stages {
        stage('Checkout') { 
            steps {
                script {
                    properties([parameters([booleanParam('test')])])
                }
                git credentialsId: "${github_creds}" , url: "${github_repo}" 
            }
        }
    }
  }
