pipeline {
    agent any

    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        string(name: 'PERSON212e12e1', defaultValue: 'Mr Jenkins2', description: 'Who should I say hello to?2')
    }
    stages {
        stage('Checkout') { 
            steps {
                git credentialsId: WOLOLO , url: git@github.com:KevinRealAlcalde/private.git
            }
        }
    }
  }
